version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: myapp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend:/var/www/html
    depends_on:
      - php
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: myapp-php
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000" 
    restart: always

  mysql:
    image: mysql:8.0
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - ./myapp.sql:/docker-entrypoint-initdb.d/myapp.sql
    ports:
      - "3306:3306"
    restart: always
