version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: myapp-nginx
    ports:
      - "8089:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - php
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: myapp-php
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000"
    restart: always

  mysql:
    image: mysql:8.0
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myapp
    volumes:
      - ./myapp.sql:/docker-entrypoint-initdb.d/myapp.sql
    ports:
      - "3306:3306"
    restart: always
